name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

jobs:
  depot-cacheless:
    name: Depot Cacheless
    runs-on: depot-ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          rm /home/runner/.bazelrc
          bazel build :grpc

  depot-remote-cache:
    name: Depot with Remote Cache
    runs-on: depot-ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: bazel build :grpc

  github-cacheless:
    name: Github Cacheless
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          bazel build :grpc

  github-actions-cache:
    name: Github with @actions/cache
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/bazel
          key: bazel-${{ hashFiles('upstream/.bazelversion', 'upstream/.bazelrc', 'upstream/WORKSPACE', 'upstream/WORKSPACE.bazel', 'upstream/MODULE.bazel') }}
      - run: bazel build :grpc

  github-setup-bazel:
    name: Github with @bazel-contrib/setup-bazel
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel build :grpc
